baseurl: ""

# Site settings
title: Chippewa Valley MLF
email: info@cvmlf.com
url: https://www.cvmlf.com
description: "A Christian bass fishing club using a Major League Fishing style format"
keywords: "bass fishing major league fishing club"
meta_author: Tony E

# Navigation
nav_rules: Rules
nav_about: About
nav_schedule: Schedule  
nav_contact: Contact
  
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3333cc
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  location: Location
  social: Around the Web
  credits: Credits

# Build settings
markdown: kramdown
permalink: pretty
